[project]
name = "practica"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "behave>=1.3.3",
    "behave-django>=1.9.0",
    "django>=6.0.2",
    "djangorestframework>=3.17.1",
    "mistune>=3.0",
    "psycopg[binary]>=3.2", # PostgreSQL driver for Django
    "splinter[django]>=0.21.0",
    "zope-testbrowser>=8.0",
]
