# Generated by Django 6.0.3 on 2026-05-11 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrieps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(default=1.2, help_text='Activity level'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=18, help_text='Age in years'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text='Biological sex for BMR calculation', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal_type',
            field=models.CharField(choices=[('L', 'Lose Weight (-300 kcal)'), ('M', 'Maintain Weight'), ('G', 'Gain Muscle (+300 kcal)')], default='M', help_text="User's weight goal", max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_weight',
            field=models.FloatField(default=0.0, help_text='Target weight in kg'),
        ),
        migrations.AlterField(
            model_name='consumptionlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(default=0.0, help_text='Height in cm'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(default=0.0, help_text='Weight in kg'),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
